clone_depth: 50
branches:
  only:
    - master
image: Visual Studio 2017
environment:
  matrix:
  - TARGET: nightly-x86_64-pc-windows-msvc
  - TARGET: nightly-i686-pc-windows-msvc
  - TARGET: nightly-x86_64-pc-windows-gnu
    MSYS_BITS: 64
  - TARGET: nightly-i686-pc-windows-gnu
    MSYS_BITS: 32
  - TARGET: beta-x86_64-pc-windows-msvc
  - TARGET: beta-i686-pc-windows-msvc
  - TARGET: beta-x86_64-pc-windows-gnu
    MSYS_BITS: 64
  - TARGET: beta-i686-pc-windows-gnu
    MSYS_BITS: 32
  - TARGET: 1.23.0-x86_64-pc-windows-msvc
  - TARGET: 1.23.0-i686-pc-windows-msvc
  - TARGET: 1.23.0-x86_64-pc-windows-gnu
    MSYS_BITS: 64
  - TARGET: 1.23.0-i686-pc-windows-gnu
    MSYS_BITS: 32

install:
  - git submodule update --init --recursive
  - ps: Start-FileDownload "https://static.rust-lang.org/dist/rust-${env:TARGET}.msi" -FileName "rust-install.msi"
  - ps: .\rust-install.msi /VERYSILENT /NORESTART /DIR="C:\rust" | Out-Null
  - ps: $env:PATH="$env:PATH;C:\rust\bin"
  - if defined MSYS_BITS set PATH=C:\msys64\mingw%MSYS_BITS%\bin;C:\msys64\usr\bin;%PATH%
  - rustc -vV
  - cargo -vV
build_script:
  - cargo build
  - cargo package
test_script:
- cargo test

